spring:
  docker:
    compose:
      enabled: true
      lifecycle-management: start_and_stop
      stop:
        command: down
        timeout: 1m
  security:
    user:
      name: user
      password: password
